### ISSUE TITLE
az spring-cloud app binding mysql add 

### ISSUE THREAD

**Issue by gustavozimm** [Azure/azure-cli-extensions#3109]
## Describe the bug

**Command Name**
`az spring-cloud app binding mysql add
Extension Name: spring-cloud. Version: 2.2.0.`

**Errors:**
```
'BindingsOperations' object has no attribute 'apps'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/spring-cloud/azext_spring_cloud/custom.py, ln 296, in _check_active_deployment_exist
    active_deployment_name = client.apps.get(resource_group, service, app).properties.active_deployment_name
AttributeError: 'BindingsOperations' object has no attribute 'apps'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring-cloud app binding mysql add --app {} --name {} --database-name {} --resource-group {} --service {} --username {} --key {} --resource-id {}`

## Environment Summary
```
Linux-5.4.0-1039-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
spring-cloud 2.2.0

```

**Comment by gustavozimm** [comment]
I tested with extension version 2.1.0 and this one worked (didn't work with version 2.1.2 and 2.2.0). 

command line:
az spring-cloud app binding mysql add \
--app todo-service \
--database-name todos \
--key $MYSQL-PWD \
--name mysql-todos \
--resource-group rg-lab-spring-cloud-001 \
--resource-id /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/rg-lab-spring-cloud-001/providers/Microsoft.DBforMySQL/servers/sc-lab-gz-001-mysql \
--service sc-lab-gz-001 \
--username <usrname>

Also, there is a bug on Azure Portal to register the service bindings, it does not list the resource group or service name. 

Thank you!

**Comment by yungezz** [comment]
route to appropriate team

**Comment by yuwzho** [comment]
Thanks for your reporting! 
@ShichaoQiu Please take a look, it seems in the serviceBinding command, we wanna [fetch the activeDeployment](https://github.com/Azure/azure-cli-extensions/blob/ecc2c6561809fc91dfdbbd886a410024a1096fcd/src/spring-cloud/azext_spring_cloud/custom.py#L1112) using the [bindingClient specified in the command](https://github.com/Azure/azure-cli-extensions/blob/ecc2c6561809fc91dfdbbd886a410024a1096fcd/src/spring-cloud/azext_spring_cloud/commands.py#L80-L89), and results in this fatal.

**Comment by yuwzho** [comment]
@gustavozimm The  fix has been applied, you can use `az extension update -n spring-cloud` to upgrade the version to `2.2.1` to have a try. Thanks again for your reporting!
