### ISSUE TITLE
Broken: az aks pod-identity add for extension aks-preview

### ISSUE THREAD

**Issue by tomarrajesh** [Azure/azure-cli-extensions#6196]
### Related command

`az aks pod-identity add`
Command reference: https://learn.microsoft.com/en-us/cli/azure/aks/pod-identity?view=azure-cli-latest#az-aks-pod-identity-add

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
I was hoping to create pod identities for an aks cluster I was working with.
I was following the article here: https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#create-a-pod-identity
Within this article, there's a step where you need to create pod-identities using the command `az aks pod-identity add`.
This command seems to be failing for the latest versions combination of azure-cli and aks-preview extension.

#### Version combination at the latest cli version as of today:
```
PS> az --version
azure-cli                         2.47.0

core                              2.47.0
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.136
```
Error observed at this combination:
```
PS> az aks pod-identity add --resource-group $CLUSTER_RESOURCE_GROUP --cluster-name $AKS_CLUSTER --namespace $POD_IDENTITY_NAMESPACE  --name $POD_IDENTITY_NAME --identity-resource-id $IDENTITY_RESOURCE_ID
'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[###                                 ]  10.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[#######                             ]  20.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[##########                          ]  30.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[##############                      ]  40.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[##################                  ]  50.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[#####################               ]  60.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[#########################           ]  70.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[############################        ]  80.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Waiting for AAD role to propagate[################################    ]  90.0000%'RoleAssignmentsOperations' object has no attribute 'config'
Could not grant Managed Identity Operator permission for cluster
```

#### Version combination that works:

```
PS> az --version
azure-cli                         2.27.2 *

core                              2.27.2 *
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.44
```
Success message observed at this combination:
```
PS> az aks pod-identity add --resource-group $CLUSTER_RESOURCE_GROUP --cluster-name $AKS_CLUSTER --namespace $POD_IDENTITY_NAMESPACE  --name $POD_IDENTITY_NAME --identity-resource-id $IDENTITY_RESOURCE_ID
AAD role propagation done[############################################]  100.0000%
Wait 30 seconds for identity role assignment propagation.
{
  "aadProfile": null,
  "addonProfiles": {
    "azurepolicy": {
      "config": null,
      "enabled": true,
....
}
```

**Comment by SaurabhSharma-MSFT** [comment]
@tomarrajesh Can you provide your OS information. Also, please run the command with `-debug` parameter and provide the output logs for further investigation. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@tomarrajesh I am not able to reproduce this.  I have tried multiple times but cmdlet worked fine with CLI version **2.47** - 
![image](https://user-images.githubusercontent.com/38112130/233713851-66ece2d2-fb53-43ec-b409-a6c88393971d.png)
![image](https://user-images.githubusercontent.com/38112130/233714036-60fffa80-866f-4b57-a893-4356af5c3223.png)

**Comment by SaurabhSharma-MSFT** [comment]
@tomarrajesh Please let us know if you are still having problems.

**Comment by SaurabhSharma-MSFT** [comment]
@tomarrajesh We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
