### ISSUE TITLE
`az interactive` crashes with "cannot import name 'ENV_ADDITIONAL_USER_AGENT'"

### ISSUE THREAD

**Issue by draptik** [Azure/azure-cli-extensions#1480]
## `az interactive` crashes

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'ENV_ADDITIONAL_USER_AGENT' from 'azure.cli.core.commands.client_factory' (/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/client_factory.py)
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 31, in <module>
    from azure.cli.core.commands.client_factory import ENV_ADDITIONAL_USER_AGENT
ImportError: cannot import name 'ENV_ADDITIONAL_USER_AGENT' from 'azure.cli.core.commands.client_factory' (/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/client_factory.py)
```

## To Reproduce:

- `az interactive --debug`

## Expected Behavior

`az interactive` should not crash.

## Environment Summary
```
Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5
Python 3.8.2
Installer: 

azure-cli 2.3.0

Extensions:
interactive 0.4.3

```
## Additional Context

Installation source: https://aur.archlinux.org/packages/azure-cli/

**Comment by jiasli** [comment]
This issue is introduced by https://github.com/Azure/azure-cli/pull/12734 which removed the redundant logic of `ENV_ADDITIONAL_USER_AGENT`, because it is already taken care of by msrest. 

I have submitted PR https://github.com/Azure/azure-cli-extensions/pull/1479 to fix it.

**Comment by yonzhan** [comment]
add to S168

**Comment by dollarpo7** [comment]
Is there a workaround for this issue?

**Comment by yonzhan** [comment]
please see the comment by @jiasli  mentioned above

**Comment by jiasli** [comment]
This issue has been fixed by https://github.com/Azure/azure-cli-extensions/pull/1479, please run `az extension update -n interactive` to get the latest version 0.4.4.

**Comment by klawrawkz** [comment]
This still happens with the latest version as of 6/29/2020.
```
PS C:\source\terraform-deploy\azure-build-agents> az --version
azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0
interactive                        0.4.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dmorrison\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

![image](https://user-images.githubusercontent.com/48074223/86052046-5e2fc780-ba24-11ea-8584-186640d1ad36.png)

I see above that there is a work-around. I navigated to the link and didn't see any work-around guidance. All I saw was that there was a PR in April that supposedly fixes this.

Since it's still happening, I'll plead _confusion_ b/c I don't believe this is fixed for me, and I don't see anything resembling a work-around.

What am I missing?

Thanks,

Klaw

**Comment by jiasli** [comment]
Hi @klawrawkz, you are using 

```
interactive                        0.4.3
```

Please run `az extension update -n interactive` to get the latest version 0.4.4.

**Comment by klawrawkz** [comment]
Hi @jiasli,

Thanks for the info. I didn't realize we needed to update extensions.  Makes sense tho, and now it's working.
