### ISSUE TITLE
az interactive fails with python 3.12

### ISSUE THREAD

**Issue by orkisz** [Azure/azure-cli-extensions#8171]
### Describe the bug

After updating brew packages, which caused setting default python3 instance to python3.13, `az interactive` stopped to work

### Related command

`az interactive`

### Errors

```
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'ConfigParser' object has no attribute 'readfp'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 11, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 111, in __init__
    self.config = Configuration(cli_ctx.config, style=style)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/configuration.py", line 76, in __init__
    self.config.readfp(config_file)  # pylint: disable=deprecated-method
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['interactive', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x102ef60c0>, <function OutputProducer.on_global_arguments at 0x1031f6de0>, <function CLIQuery.on_global_arguments at 0x1032385e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'interactive': ['azure.cli.command_modules.interactive']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: interactive               0.001         1         1
cli.azure.cli.core: Total (1)                 0.001         1         1
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 1 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : interactive
cli.azure.cli.core: Command table: interactive
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x104771260>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/ko/.azure/commands/2024-10-21.10-22-33.interactive.12563.log'.
az_command_data_logger: command args: interactive --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1047bed40>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1047e5080>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1047e51c0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x1047e5260>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x1031f6e80>, <function CLIQuery.handle_query_parameter at 0x103238680>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1047e5120>]
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 11, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 111, in __init__
    self.config = Configuration(cli_ctx.config, style=style)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/configuration.py", line 76, in __init__
    self.config.readfp(config_file)  # pylint: disable=deprecated-method
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'ConfigParser' object has no attribute 'readfp'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 11, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 111, in __init__
    self.config = Configuration(cli_ctx.config, style=style)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/configuration.py", line 76, in __init__
    self.config.readfp(config_file)  # pylint: disable=deprecated-method
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
az_command_data_logger: 'ConfigParser' object has no attribute 'readfp'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 11, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 111, in __init__
    self.config = Configuration(cli_ctx.config, style=style)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ko/.azure/cliextensions/interactive/azext_interactive/azclishell/configuration.py", line 76, in __init__
    self.config.readfp(config_file)  # pylint: disable=deprecated-method
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1047714e0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.302 seconds (init: 0.120, invoke: 0.182)
```

### Expected behavior

Expect `az interactive` to start interactive session

### Environment Summary

```
azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1
interactive                        0.5.3
logic                              1.1.0
ml                                2.31.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.65.0_1/libexec/bin/python'
Extensions directory '/Users/ko/.azure/cliextensions'

Python (Darwin) 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by orkisz** [comment]
Updade: issue is no longer present after updating `azure-cli` from 2.65.0_1 to 2.65.0_2 which reverted Python dependency back to 3.11

**Comment by ReaNAiveD** [comment]
The extension `interactive` used `ConfigParser.readfp` which is no longer supported in `Python 3.12`.

**Comment by orkisz** [comment]
Issue appeared again after updating `azure-cli` from  `2.65.0_2` to `2.66.0`. Please reopen

**Comment by ReaNAiveD** [comment]
Hi @orkisz , Could you please run `az --version` to verify if the interactive extension has been updated to version `1.0.0b1` or newer?

**Comment by orkisz** [comment]
Before the manual upgrade:

```
⋊> ~ az --version                                                                                                                                                                                                                   08:54:28
azure-cli                         2.66.0

core                              2.66.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1
interactive                        0.5.3
logic                              1.1.0
ml                                2.31.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.66.0/libexec/bin/python'
Extensions directory '/Users/ko/.azure/cliextensions'

Python (Darwin) 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

After I did manual upgrade by `az upgrade`:
```
⋊> ~ az --version                                                                                                                                                                                                                   08:56:40
azure-cli                         2.66.0

core                              2.66.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1
interactive                      1.0.0b1
logic                              1.1.0
ml                                2.32.1

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.66.0/libexec/bin/python'
Extensions directory '/Users/ko/.azure/cliextensions'

Python (Darwin) 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date
```

And now it seems the problem is gone. Thank you :)

**Comment by ondrejkolin** [comment]
Is this bug still present?

~ ondrej(aks_alpha-k8s-admin) $ az --version
azure-cli                         2.74.0

core                              2.74.0
telemetry                          1.1.0

Extensions:
interactive                        0.5.3

Dependencies:
msal                              1.32.3
azure-mgmt-resource               23.3.0

Python location '/usr/bin/python3.12'
Config directory '/home/ondrej/.azure'
Extensions directory '/home/ondrej/.azure/cliextensions'

Python (Linux) 3.12.10 (main, May  9 2025, 00:00:00) [GCC 15.1.1 20250425 (Red Hat 15.1.1-1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
~ ondrej(aks_alpha-k8s-admin) $ az interactive
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'ConfigParser' object has no attribute 'readfp'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 120, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/ondrej/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 11, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ondrej/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 111, in __init__
    self.config = Configuration(cli_ctx.config, style=style)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ondrej/.azure/cliextensions/interactive/azext_interactive/azclishell/configuration.py", line 76, in __init__
    self.config.readfp(config_file)  # pylint: disable=deprecated-method
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**Comment by ondrejkolin** [comment]
@ReaNAiveD can you please reopen the issue if it's applicable?

**Comment by ondrejkolin** [comment]
What's puzzling me, that the problematic file is in my user's home. So it might be a problem introduced by myself ... I've manually changed the affected line and now it's starting again.

**Comment by ReaNAiveD** [comment]
You can solve the issue by installing the latest version of `az interactive`, which is compatible with Python 3.12, using the `az upgrade` command.

> What's puzzling me, that the problematic file is in my user's home. So it might be a problem introduced by myself ... I've manually changed the affected line and now it's starting again.

Azure CLI extensions are designed to be installed in `$home/.azure/cliextensions`.
