### ISSUE TITLE
az interactive will not work with azure-cli 2.0.62.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-extensions#629]
(env) D:\GitRepos\github>az interactive
Installing the Interactive extension..
The installed extension 'interactive' is in preview.
The command failed with an unexpected error. Here is the traceback:

cannot import name 'DEFAULTS_SECTION' from 'azure.cli.core._config' (d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\_config.py)
Traceback (most recent call last):
  File "D:\GitRepos\github\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 397, in execute
    raise ex
  File "d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 455, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 448, in _run_job
    six.reraise(*sys.exc_info())
  File "D:\GitRepos\github\env\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 425, in _run_job
    result = cmd_copy(params)
  File "d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 454, in default_command_handler
    return op(**command_args)
  File "d:\gitrepos\github\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\custom.py", line 31, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "C:\Users\trpresco\.azure\cliextensions\interactive\azext_interactive\__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "C:\Users\trpresco\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION' from 'azure.cli.core._config' (d:\gitrepos\github\azure-cli\src\azure-cli-core\azure\cli\core\_config.py)

To open an issue, please run: 'az feedback'
