### PR TITLE
{CI} Support codespace

### PR DESCRIPTION
**Pull request by wangzelin007**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

1. Use the latest official python3.11 image
2. Create a python virtual environment in the /home/vscode directory
3. The following plug-ins are installed by default:
   - editorconfig.editorconfig
   - github.vscode-pull-request-github
   - ms-azuretools.vscode-docker
   - ms-python.python
   - ms-python.flake8
   - github-cli
4. Clone azure-cli and azure-cli-extensions in the /workspaces directory
5. Automatically setup development environment
6. Automatically activate python virtual environment

screenshot：

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
CI

**Comment by wangzelin007** [comment]
If anyone wants to debug with vscode, here is an example configuration for `.vscode/launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Codespace Azure CLI Debug",
            "type": "python",
            "request": "launch",
            "python": "/home/vscode/env/bin/python",
            "program": "${workspaceRoot}/src/azure-cli/azure/cli/__main__.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "--help"
            ],
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "justMyCode": false
        },
        {
            "name": "Codespace Azdev Debug",
            "type": "python",
            "request": "launch",
            "python": "/home/vscode/env/bin/python",
            "program": "/home/vscode/env/lib/python3.11/site-packages/azdev/__main__.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "--help"
            ],
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```

File: .flake8 [hunk 1]
```diff
@@ -2,13 +2,20 @@
...
 max-complexity = 10
 ignore =
-    E501,  # line too long, it is covered by pylint
-    E722,  # bare except, bad practice, to be removed in the future
-    F401,  # imported but unused, too many violations, to be removed in the future
-    F811,  # redefinition of unused, to be removed in the future
-    C901   # code flow is too complex, too many violations, to be removed in the future
-    W503   # line break before binary operator effect on readability is subjective
-    W504   # line break after binary operator effect on readability is subjective
+    # line too long, it is covered by pylint
```
Comment (wangzelin007) [inline .flake8:5]: This issue was caused by the updating of flake8 to 6.
image

**Comment by haitch** [comment]
what blocks  this PR from merge?  we can get it merged and keep evolving, right?

**Comment by wangzelin007** [comment]
> what blocks this PR from merge? we can get it merged and keep evolving, right?

Sorry, due to security considerations, we do not plan to directly support the codespace. 
If you really need this function, please [create an issue](https://github.com/Azure/azure-cli-extensions/issues) and we will discuss it with PM.

**Comment by jessehouwing** [comment]
@wangzelin007 I tried contributing to this repo, but the steps to setup are many, the docs was hard to find, and in the end half of the things I needed to do still didn't work. Havig a codespace in which the code formatting, linting, compiling and running the tests just works is going to make it soooo much easier for external people like me to contribute.

I'd love to understand the security considerations. 

I have already filed https://github.com/Azure/azure-cli-extensions/issues/6794 with my reasoning.

**Comment by wangzelin007** [comment]
Hi @jiasli,
Can you help describe the security issues we encountered on GitHub Action and our concerns about GitHub codespace?
