### ISSUE TITLE
Latest storage-preview causing error with "update" in az storage blob service-properties

### ISSUE THREAD

**Issue by bhavya-teja** [Azure/azure-cli-extensions#470]
### Extension name (the extension in question)
storage-preview

### Description of issue (in as much detail as possible)
"update" not available in az storage blob service-properties after updating storage preview to latest (working fine before latest update)

C:\WINDOWS\system32>az -v
azure-cli (2.0.51)
...
storage-preview (0.2.1)

Warning message being displayed "Unable to load extension 'storage-preview'. Use --debug for more information."

Works fine with latest azure-cli (2.0.54) apologies if this was mentioned in documentation somewhere

**Comment by davidobrien1985** [comment]
Same error here. Any way to solve this soon?

**Comment by davidobrien1985** [comment]
```
bash-4.4# az --version
azure-cli (2.0.55)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
botservice (0.1.4)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.2.0)
interactive (0.3.27)
iot (0.2.0)
iotcentral (0.1.5)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
relay (0.1.2)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
signalr (1.0.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Extensions:
storage-preview (0.2.1)

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.4 (default, Jan 10 2018, 05:20:21)
```

literally every `az` command throws an error:
```

**Comment by davidobrien1985** [comment]
debug:
```
bash-4.4# az extension list --debug
Command arguments: ['extension', 'list', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fc47a909378>, <function OutputProducer.on_global_arguments at 0x7fc47a6b5950>, <function CLIQuery.on_global_arguments at 0x7fc47a6cc488>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7fc47a909400>]
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'servicebus', 'servicefabric', 'signalr', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.008 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.010 seconds.
Loaded module 'appservice' in 0.011 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.018 seconds.
Loaded module 'batchai' in 0.005 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.007 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'dla' in 0.006 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.003 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.008 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'lab' in 0.006 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'network' in 0.034 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.005 seconds.
Loaded module 'redis' in 0.004 seconds.
Loaded module 'relay' in 0.004 seconds.
Loaded module 'reservations' in 0.004 seconds.
Loaded module 'resource' in 0.027 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'servicebus' in 0.008 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.008 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.029 seconds.
Loaded module 'vm' in 0.016 seconds.
Loaded all modules in 0.307 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/root/.azure/cliextensions'
Found 1 extensions: ['storage-preview']
Event: CommandLoader.OnLoadCommandTable []
Event: MainLoader.OnFailedExtensionLoad []
Unable to load extension 'storage-preview'. Use --debug for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 183, in _update_command_table_from_extensions
    _load_extension_command_loader(self, args, ext_mod)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 614, in _load_extension_command_loader
    return _load_command_loader(loader, args, ext, '')
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 600, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "/root/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 33, in load_command_table
    load_command_table(self, args)
  File "/root/.azure/cliextensions/storage-preview/azext_storage_preview/commands.py", line 91, in load_command_table
    g.storage_command_oauth('show', 'get_blob_service_properties', exception_handler=show_exception_handler)
  File "/root/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 156, in storage_command_oauth
    self.storage_command(*args, oauth=True, **kwargs)
  File "/root/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 152, in storage_command
    self._register_data_plane_oauth_arguments(command_name)
  File "/root/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 237, in _register_data_plane_oauth_arguments
    help='The mode in which to run the command. "login" mode will directly use your login credentials '
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/parameters.py", line 479, in extra
    if not self._applicable():
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/parameters.py", line 333, in _applicable
    return command_name.startswith(scope)
AttributeError: 'NoneType' object has no attribute 'startswith'

Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7fc479e5fae8>, <function register_global_subscription_parameter.<locals>.add_subscription_parameter at 0x7fc479e388c8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fc47995f1e0>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fc47a6b59d8>, <function CLIQuery.handle_query_parameter at 0x7fc47a6cc510>, <function register_global_subscription_parameter.<locals>.parse_subscription_parameter at 0x7fc479df72f0>, <function handler at 0x7fc4798be620>]
Extensions directory: '/root/.azure/cliextensions'
Extensions directory: '/root/.azure/cliextensions'
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7fc479e6ad08>, <function _x509_from_base64_to_hex_transform at 0x7fc479e6ad90>]
Event: CommandInvoker.OnFilterResult []
[
  {
    "extensionType": "whl",
    "name": "storage-preview",
    "version": "0.2.1"
  }
]
Event: Cli.PostExecute []
```

**Comment by davidobrien1985** [comment]
started working now on a clean installation of `azure-cli`

**Comment by williexu** [comment]
Storage extension should work with CLI versions above 2.0.52, version constraint in extension was outdated and updated with : https://github.com/Azure/azure-cli-extensions/pull/474
