### PR TITLE
Update the minimum az cli version to 2.11.0 for vmware

### LINKED ISSUE #3045: vmware 2.0.0 does not work in azure-cli:2.7.0
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
vmware

### Description of issue (in as much detail as possible)
The  vmware 2.0.0 extension released yesterday does not work with the az cli 2.7.0 released on 2020-06-01, about 9 months ago.  I'm not sure exactly what the minimum version should be set to. 

I believe this needs to be updated, but I'm not sure what it should be or what the best process is for updating it.
https://github.com/Azure/azure-cli-extensions/blob/master/src/vmware/azext_vmware/azext_metadata.json
```
"azext.minCliCoreVersion": "2.0.66"
```

image

steps to reproduce:
```
docker run --rm -it mcr.microsoft.com/azure-cli:2.7.0
az extension add -n vmware
az vmware private-cloud show -g taggac-2020-12 -n taggac-20210219
```

Here are the 
```
PS C:\Users\cataggar\io\fct> docker run --rm -it mcr.microsoft.com/azure-cli:2.7.0
bash-5.0# az extension add -n vmware
bash-5.0# az vmware private-cloud show -g taggac-2020-12 -n taggac-20210219
The command failed with an unexpected error. Here is the traceback:

cannot import name 'ARMHttpLoggingPolicy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 344, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 723, in generic_show_arguments_loader
    cmd_args = get_arguments_loader(context, getter_op, operation_group=kwargs.get('operation_group'))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 402, in get_arguments_loader
    getter_args = dict(extract_args_from_signature(context.get_op_handler(getter_op, operation_group=operation_group),
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 588, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.azure/cliextensions/vmware/azext_vmware/custom.py", line 7, in <module>
    from azext_vmware.vendored_sdks.avs_client import AVSClient
  File "/root/.azure/cliextensions/vmware/azext_vmware/vendored_sdks/avs_client/__init__.py", line 7, in <module>
    from ._avs_client import AVSClient
  File "/root/.azure/cliextensions/vmware/azext_vmware/vendored_sdks/avs_client/_avs_client.py", line 18, in <module>
    from ._configuration import AVSClientConfiguration
  File "/root/.azure/cliextensions/vmware/azext_vmware/vendored_sdks/avs_client/_configuration.py", line 11, in <module>    from azure.mgmt.core.policies import ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMHttpLoggingPolicy'

To open an issue, please run: 'az feedback'
bash-5.0#
```

-----

### PR DESCRIPTION
**Pull request by ctaggart**
Fixes #3045. Please publish.

### CODE REVIEW

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
@ctaggart Thanks for fixing it!
