### ISSUE TITLE
vmware 2.0.0 does not work in azure-cli:2.7.0

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-extensions#3045]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
vmware

### Description of issue (in as much detail as possible)
The  vmware 2.0.0 extension released yesterday does not work with the az cli 2.7.0 released on 2020-06-01, about 9 months ago.  I'm not sure exactly what the minimum version should be set to. 

I believe this needs to be updated, but I'm not sure what it should be or what the best process is for updating it.
https://github.com/Azure/azure-cli-extensions/blob/master/src/vmware/azext_vmware/azext_metadata.json
```
"azext.minCliCoreVersion": "2.0.66"
```

![image](https://user-images.githubusercontent.com/80104/109070352-3f62fd00-76a7-11eb-8151-e474f1edba71.png)

steps to reproduce:
```
docker run --rm -it mcr.microsoft.com/azure-cli:2.7.0
az extension add -n vmware
az vmware private-cloud show -g taggac-2020-12 -n taggac-20210219
```

Here are the 
```
PS C:\Users\cataggar\io\fct> docker run --rm -it mcr.microsoft.com/azure-cli:2.7.0
bash-5.0# az extension add -n vmware
bash-5.0# az vmware private-cloud show -g taggac-2020-12 -n taggac-20210219
The command failed with an unexpected error. Here is the traceback:

cannot import name 'ARMHttpLoggingPolicy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 344, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 723, in generic_show_arguments_loader
    cmd_args = get_arguments_loader(context, getter_op, operation_group=kwargs.get('operation_group'))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 402, in get_arguments_loader
    getter_args = dict(extract_args_from_signature(context.get_op_handler(getter_op, operation_group=operation_group),
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 588, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.azure/cliextensions/vmware/azext_vmware/custom.py", line 7, in <module>
    from azext_vmware.vendored_sdks.avs_client import AVSClient
  File "/root/.azure/cliextensions/vmware/azext_vmware/vendored_sdks/avs_client/__init__.py", line 7, in <module>
    from ._avs_client import AVSClient
  File "/root/.azure/cliextensions/vmware/azext_vmware/vendored_sdks/avs_client/_avs_client.py", line 18, in <module>
    from ._configuration import AVSClientConfiguration
  File "/root/.azure/cliextensions/vmware/azext_vmware/vendored_sdks/avs_client/_configuration.py", line 11, in <module>    from azure.mgmt.core.policies import ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMHttpLoggingPolicy'

To open an issue, please run: 'az feedback'
bash-5.0#
```

-----

**Comment by ctaggart** [comment]
I tried out the different azure-cli docker images and determined that 2.11.0 was the minimum version. I created pull request #3046 to set that as the minimum version. For users, who do not wish to upgrade, you can install version 1.0.0 using:

```
az extension remove -n vmware
az extension add -s https://azcliprod.blob.core.windows.net/cli-extensions/vmware-1.0.0-py2.py3-none-any.whl -y
az extension show -n vmware
```

**Comment by ctaggart** [comment]
Unfortunately, even with 2.0.1 released, the steps to reproduce above lead to the same error. `az extension add -n vmware` sees that 2.0.1 is not compatible and installs 2.0.0. 2.0.0 needs to be removed from the index, so that 1.0.0 is installed instead.

**Comment by yungezz** [comment]
> Unfortunately, even with 2.0.1 released, the steps to reproduce above lead to the same error. `az extension add -n vmware` sees that 2.0.1 is not compatible and installs 2.0.0. 2.0.0 needs to be removed from the index, so that 1.0.0 is installed instead.

hi @ctaggart do you mean that index file should only keeps 1.0.0 and 2.0.1? if a user installed 1.0.0 already, is it ok to upgrade to 2.0.1? cc @fengzhou-msft for index.json change

**Comment by ctaggart** [comment]
@yungezz, in #3056, I remove 2.0.0 from the index so that when `az extension add -n vmware` is run by az cli versions older than az cli 2.11.0, they will install version 1.0.0. I believe they use the latest version that is compatible by looking at the "azext.minCliCoreVersion"s in index.json.

**Comment by ctaggart** [comment]
I just confirmed that this is now fixed with #3056 merged as well to update the index.
