### PR TITLE
[Interactive] Remove dependency of ENV_ADDITIONAL_USER_AGENT

### LINKED ISSUE #1480: `az interactive` crashes with "cannot import name 'ENV_ADDITIONAL_USER_AGENT'"
## `az interactive` crashes

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'ENV_ADDITIONAL_USER_AGENT' from 'azure.cli.core.commands.client_factory' (/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/client_factory.py)
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 31, in <module>
    from azure.cli.core.commands.client_factory import ENV_ADDITIONAL_USER_AGENT
ImportError: cannot import name 'ENV_ADDITIONAL_USER_AGENT' from 'azure.cli.core.commands.client_factory' (/opt/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/client_factory.py)
```

## To Reproduce:

- `az interactive --debug`

## Expected Behavior

`az interactive` should not crash.

## Environment Summary
```
Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5
Python 3.8.2
Installer: 

azure-cli 2.3.0

Extensions:
interactive 0.4.3

```
## Additional Context

Installation source: https://aur.archlinux.org/packages/azure-cli/

### PR DESCRIPTION
**Pull request by jiasli**
Fix #1480: `az interactive` crashes with "cannot import name 'ENV_ADDITIONAL_USER_AGENT'"

This issue is introduced by https://github.com/Azure/azure-cli/pull/12734 which removed the redundant logic of `ENV_ADDITIONAL_USER_AGENT`, because it is already taken care of by msrest. 

This PR removes the dependency of `AZURE_HTTP_USER_AGENT` and hard-codes it because msrest doesn't expose it:

https://github.com/Azure/msrest-for-python/blob/4cc8bc84e96036f03b34716466230fb257e27b36/msrest/pipeline/universal.py#L70

```py
class UserAgentPolicy(SansIOHTTPPolicy):
    _USERAGENT = "User-Agent"
    _ENV_ADDITIONAL_USER_AGENT = 'AZURE_HTTP_USER_AGENT'
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S168

File: src/interactive/azext_interactive/azclishell/app.py [hunk 1]
```diff
@@ -98,7 +98,7 @@ def __init__(self, cli_ctx, style=None, completer=None,
             self.completer = AzCompleter(self, None)
             self.lexer = None
         self.history = history or FileHistory(os.path.join(self.config.get_config_dir(), self.config.get_history()))
-        os.environ[ENV_ADDITIONAL_USER_AGENT] = 'AZURECLISHELL/' + VERSION
+        os.environ[_ENV_ADDITIONAL_USER_AGENT] = 'AZURECLISHELL/' + VERSION
```
Comment (fengzhou-msft) [inline src/interactive/azext_interactive/azclishell/app.py:101]: If `AZURE_HTTP_USER_AGENT` is already set, this will overwrite it.

Comment (jiasli) [reply src/interactive/azext_interactive/azclishell/app.py]: Good point! Changed as requested.
